import os

JIRA_URL = os.getenv('JIRA_URL', 'JIRA_URL')
JIRA_EMAIL = os.getenv('JIRA_EMAIL', 'JIRA_EMAIL')
JIRA_API_TOKEN = os.getenv('JIRA_API_TOKEN', 'JIRA_API_TOKEN')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', 'OPENAI_API_KEY')
